### ISSUE TITLE
pcap.h was not found

### ISSUE THREAD

**Issue by 10186937** [cnplab/blockmon#3]
Hi,
On the main directory, I type `cmake .` , it seams well.
When cmake is finished, I type `make`.
This is what I get:
[  1%] Building CXX object CMakeFiles/blockmoncore.dir/blocks/PcapSource.cpp.o
/home/qlq/blockmon/blocks/PcapSource.cpp:85:18: 致命错误：pcap.h：没有那个文件或目录
 #include <pcap.h>
                  ^
编译中断。
make[2]: *** [CMakeFiles/blockmoncore.dir/blocks/PcapSource.cpp.o] 错误 1
make[1]: *** [CMakeFiles/blockmoncore.dir/all] 错误 2
make: *** [all] 错误 2
Thanks!

**Comment by 10186937** [comment]
After I installed libpcap-devel pkg,  it seamed well.

**Comment by jmmlmendes** [comment]
That is correct, it's not on the instructions (maybe it should?) but the libpcap headers are necessary in order to build blockmon with the PcapSource block.

Since it's working now, could you close this issue?
Thanks!

**Comment by 10186937** [comment]
Thank you jmmlmendes.
